// swift-tools-version:5.9
//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftCrypto open source project
//
// Copyright (c) 2019-2023 Apple Inc. and the SwiftCrypto project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.md for the list of SwiftCrypto project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// This package contains a vendored copy of BoringSSL. For ease of tracking
// down problems with the copy of BoringSSL in use, we include a copy of the
// commit hash of the revision of BoringSSL included in the given release.
// This is also reproduced in a file called hash.txt in the
// Sources/CCryptoBoringSSL directory. The source repository is at
// https://boringssl.googlesource.com/boringssl.
//
// BoringSSL Commit: 6a2ccdcc2ed1d37a43a2183658d2ae61fd5ce208

import PackageDescription

// To develop this on Apple platforms, set this to true
let development = false

let swiftSettings: [SwiftSetting]
let dependencies: [Target.Dependency]
if development {
    swiftSettings = [
        .define("CRYPTO_IN_SWIFTPM"),
        .define("CRYPTO_IN_SWIFTPM_FORCE_BUILD_API"),
    ]
    dependencies = [
        "CBoringSSL",
        "CCryptoBoringSSLShims",
        "CryptoBoringWrapper"
    ]
} else {
    let platforms: [Platform] = [
        Platform.linux,
        Platform.android,
        Platform.windows,
        Platform.wasi,
    ]
    swiftSettings = [
        .define("CRYPTO_IN_SWIFTPM"),
        .define("CRYPTO_IN_SWIFTPM_FORCE_BUILD_API", .when(platforms: platforms)),
    ]
    dependencies = [
        .target(name: "CBoringSSL", condition: .when(platforms: platforms)),
        .target(name: "CCryptoBoringSSLShims", condition: .when(platforms: platforms)),
        .target(name: "CryptoBoringWrapper", condition: .when(platforms: platforms))
    ]
}

let package = Package(
    name: "swift-crypto",
    platforms: [
        .macOS(.v10_15),
        .iOS(.v13),
        .watchOS(.v6),
        .tvOS(.v13),
    ],
    products: [
        .library(name: "Crypto", targets: ["Crypto"]),
        .library(name: "_CryptoExtras", targets: ["_CryptoExtras"]),
        .library(name: "CBoringSSL", targets: ["CBoringSSL"]),
    ],
    dependencies: [],
    targets: [
        .target(
            name: "CBoringSSL",
            path: ".",
            exclude: [
                "Vendors/BoringSSL/crypto/abi_self_test.cc",
                "Vendors/BoringSSL/crypto/asn1/asn1_test.cc",
                "Vendors/BoringSSL/crypto/base64/base64_test.cc",
                "Vendors/BoringSSL/crypto/bio/bio_test.cc",
                "Vendors/BoringSSL/crypto/blake2/blake2b256_tests.txt",
                "Vendors/BoringSSL/crypto/blake2/blake2_test.cc",
                "Vendors/BoringSSL/crypto/buf/buf_test.cc",
                "Vendors/BoringSSL/crypto/bytestring/bytestring_test.cc",
                "Vendors/BoringSSL/crypto/chacha/asm",
                "Vendors/BoringSSL/crypto/chacha/chacha_test.cc",
                "Vendors/BoringSSL/crypto/cipher_extra/asm",
                "Vendors/BoringSSL/crypto/cipher_extra/cipher_test.cc",
                "Vendors/BoringSSL/crypto/cipher_extra/test",
                "Vendors/BoringSSL/crypto/cipher_extra/aead_test.cc",
                "Vendors/BoringSSL/crypto/compiler_test.cc",
                "Vendors/BoringSSL/crypto/conf/conf_test.cc",
                "Vendors/BoringSSL/crypto/constant_time_test.cc",
                "Vendors/BoringSSL/crypto/cpu_arm_linux_test.cc",
                "Vendors/BoringSSL/crypto/crypto_test.cc",
                "Vendors/BoringSSL/crypto/curve25519/ed25519_test.cc",
                "Vendors/BoringSSL/crypto/curve25519/ed25519_tests.txt",
                "Vendors/BoringSSL/crypto/curve25519/make_curve25519_tables.py",
                "Vendors/BoringSSL/crypto/curve25519/spake25519_test.cc",
                "Vendors/BoringSSL/crypto/curve25519/x25519_test.cc",
                "Vendors/BoringSSL/crypto/dh_extra/dh_test.cc",
                "Vendors/BoringSSL/crypto/digest_extra/digest_test.cc",
                "Vendors/BoringSSL/crypto/dilithium/dilithium_test.cc",
                "Vendors/BoringSSL/crypto/dilithium/dilithium_tests.txt",
                "Vendors/BoringSSL/crypto/dilithium/edge_cases_draft_dilithium3_sign.txt",
                "Vendors/BoringSSL/crypto/dilithium/edge_cases_draft_dilithium3_verify.txt",
                "Vendors/BoringSSL/crypto/dsa/dsa_test.cc",
                "Vendors/BoringSSL/crypto/ecdh_extra/ecdh_test.cc",
                "Vendors/BoringSSL/crypto/ecdh_extra/ecdh_tests.txt",
                "Vendors/BoringSSL/crypto/err/asn1.errordata",
                "Vendors/BoringSSL/crypto/err/bio.errordata",
                "Vendors/BoringSSL/crypto/err/bn.errordata",
                "Vendors/BoringSSL/crypto/err/cipher.errordata",
                "Vendors/BoringSSL/crypto/err/conf.errordata",
                "Vendors/BoringSSL/crypto/err/dh.errordata",
                "Vendors/BoringSSL/crypto/err/digest.errordata",
                "Vendors/BoringSSL/crypto/err/dsa.errordata",
                "Vendors/BoringSSL/crypto/err/ec.errordata",
                "Vendors/BoringSSL/crypto/err/ecdh.errordata",
                "Vendors/BoringSSL/crypto/err/ecdsa.errordata",
                "Vendors/BoringSSL/crypto/err/engine.errordata",
                "Vendors/BoringSSL/crypto/err/err_test.cc",
                "Vendors/BoringSSL/crypto/err/evp.errordata",
                "Vendors/BoringSSL/crypto/err/hkdf.errordata",
                "Vendors/BoringSSL/crypto/err/obj.errordata",
                "Vendors/BoringSSL/crypto/err/pem.errordata",
                "Vendors/BoringSSL/crypto/err/pkcs7.errordata",
                "Vendors/BoringSSL/crypto/err/pkcs8.errordata",
                "Vendors/BoringSSL/crypto/err/rsa.errordata",
                "Vendors/BoringSSL/crypto/err/ssl.errordata",
                "Vendors/BoringSSL/crypto/err/trust_token.errordata",
                "Vendors/BoringSSL/crypto/err/x509.errordata",
                "Vendors/BoringSSL/crypto/err/x509v3.errordata",
                "Vendors/BoringSSL/crypto/evp/evp_extra_test.cc",
                "Vendors/BoringSSL/crypto/evp/evp_test.cc",
                "Vendors/BoringSSL/crypto/evp/evp_tests.txt",
                "Vendors/BoringSSL/crypto/evp/pbkdf_test.cc",
                "Vendors/BoringSSL/crypto/evp/scrypt_test.cc",
                "Vendors/BoringSSL/crypto/evp/scrypt_tests.txt",
                "Vendors/BoringSSL/crypto/fipsmodule/FIPS.md",
                "Vendors/BoringSSL/crypto/fipsmodule/aes/aes.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/aes/aes_nohw.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/aes/aes_test.cc",
                "Vendors/BoringSSL/crypto/fipsmodule/aes/aes_tests.txt",
                "Vendors/BoringSSL/crypto/fipsmodule/aes/asm",
                "Vendors/BoringSSL/crypto/fipsmodule/aes/key_wrap.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/aes/mode_wrappers.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/add.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/asm",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/bn.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/bn_test.cc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/bn_test_to_fuzzer.go",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/bytes.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/check_bn_tests.go",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/cmp.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/ctx.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/div.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/div_extra.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/exponentiation.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/gcd.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/gcd_extra.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/generic.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/jacobi.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/montgomery.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/montgomery_inv.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/mul.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/prime.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/random.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/rsaz_exp.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/shift.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/sqrt.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/bn/test",
                "Vendors/BoringSSL/crypto/fipsmodule/cipher/aead.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/cipher/cipher.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/cipher/e_aes.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/cipher/e_aesccm.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/cmac/cavp_3des_cmac_tests.txt",
                "Vendors/BoringSSL/crypto/fipsmodule/cmac/cavp_aes128_cmac_tests.txt",
                "Vendors/BoringSSL/crypto/fipsmodule/cmac/cavp_aes192_cmac_tests.txt",
                "Vendors/BoringSSL/crypto/fipsmodule/cmac/cavp_aes256_cmac_tests.txt",
                "Vendors/BoringSSL/crypto/fipsmodule/cmac/cmac_test.cc",
                "Vendors/BoringSSL/crypto/fipsmodule/cmac/cmac.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/dh/check.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/dh/dh.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/digest/digest.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/digest/digests.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/digestsign/digestsign.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/asm",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/ec.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/ec_key.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/ec_montgomery.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/ec_scalar_base_mult_tests.txt",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/ec_test.cc",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/felem.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/make_ec_scalar_base_mult_tests.go",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/make_p256-nistz-tests.go",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/make_tables.go",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/oct.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/p224-64.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/p256-nistz.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/p256-nistz_test.cc",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/p256-nistz_tests.txt",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/p256_test.cc",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/p256.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/scalar.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/simple.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/simple_mul.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/util.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/ec/wnaf.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/ecdh/ecdh.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/ecdsa/ecdsa.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/ecdsa/ecdsa_sign_tests.txt",
                "Vendors/BoringSSL/crypto/fipsmodule/ecdsa/ecdsa_test.cc",
                "Vendors/BoringSSL/crypto/fipsmodule/ecdsa/ecdsa_verify_tests.txt",
                "Vendors/BoringSSL/crypto/fipsmodule/fips_shared.lds",
                "Vendors/BoringSSL/crypto/fipsmodule/hkdf/hkdf_test.cc",
                "Vendors/BoringSSL/crypto/fipsmodule/hkdf/hkdf.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/hmac/hmac.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/intcheck1.png",
                "Vendors/BoringSSL/crypto/fipsmodule/intcheck2.png",
                "Vendors/BoringSSL/crypto/fipsmodule/intcheck3.png",
                "Vendors/BoringSSL/crypto/fipsmodule/modes/asm",
                "Vendors/BoringSSL/crypto/fipsmodule/modes/cbc.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/modes/cfb.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/modes/ctr.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/modes/gcm.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/modes/gcm_nohw.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/modes/gcm_test.cc",
                "Vendors/BoringSSL/crypto/fipsmodule/modes/gcm_tests.txt",
                "Vendors/BoringSSL/crypto/fipsmodule/modes/ofb.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/modes/polyval.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/policydocs",
                "Vendors/BoringSSL/crypto/fipsmodule/rand/asm",
                "Vendors/BoringSSL/crypto/fipsmodule/rand/ctrdrbg.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/rand/ctrdrbg_test.cc",
                "Vendors/BoringSSL/crypto/fipsmodule/rand/ctrdrbg_vectors.txt",
                "Vendors/BoringSSL/crypto/fipsmodule/rand/rand.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/rsa/blinding.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/rsa/padding.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/rsa/rsa.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/rsa/rsa_impl.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/self_check/fips.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/self_check/self_check.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/service_indicator/service_indicator.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/service_indicator/service_indicator_test.cc",
                "Vendors/BoringSSL/crypto/fipsmodule/sha/asm",
                "Vendors/BoringSSL/crypto/fipsmodule/sha/sha1.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/sha/sha256.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/sha/sha512.c.inc",
                "Vendors/BoringSSL/crypto/fipsmodule/sha/sha_test.cc",
                "Vendors/BoringSSL/crypto/fipsmodule/tls/kdf.c.inc",
                "Vendors/BoringSSL/crypto/hmac_extra/hmac_test.cc",
                "Vendors/BoringSSL/crypto/hmac_extra/hmac_tests.txt",
                "Vendors/BoringSSL/crypto/hpke/hpke_test.cc",
                "Vendors/BoringSSL/crypto/hpke/hpke_test_vectors.txt",
                "Vendors/BoringSSL/crypto/hpke/test-vectors.json",
                "Vendors/BoringSSL/crypto/hpke/translate_test_vectors.py",
                "Vendors/BoringSSL/crypto/hrss/hrss_test.cc",
                "Vendors/BoringSSL/crypto/impl_dispatch_test.cc",
                "Vendors/BoringSSL/crypto/keccak/keccak_test.cc",
                "Vendors/BoringSSL/crypto/keccak/keccak_tests.txt",
                "Vendors/BoringSSL/crypto/kyber/kyber_test.cc",
                "Vendors/BoringSSL/crypto/kyber/kyber_tests.txt",
                "Vendors/BoringSSL/crypto/lhash/lhash_test.cc",
                "Vendors/BoringSSL/crypto/md5/asm",
                "Vendors/BoringSSL/crypto/md5/md5_test.cc",
                "Vendors/BoringSSL/crypto/mldsa/mldsa_nist_keygen_tests.txt",
                "Vendors/BoringSSL/crypto/mldsa/mldsa_nist_siggen_tests.txt",
                "Vendors/BoringSSL/crypto/mldsa/mldsa_test.cc",
                "Vendors/BoringSSL/crypto/mlkem/mlkem1024_decap_tests.txt",
                "Vendors/BoringSSL/crypto/mlkem/mlkem1024_encap_tests.txt",
                "Vendors/BoringSSL/crypto/mlkem/mlkem1024_keygen_tests.txt",
                "Vendors/BoringSSL/crypto/mlkem/mlkem1024_nist_decap_tests.txt",
                "Vendors/BoringSSL/crypto/mlkem/mlkem1024_nist_keygen_tests.txt",
                "Vendors/BoringSSL/crypto/mlkem/mlkem768_decap_tests.txt",
                "Vendors/BoringSSL/crypto/mlkem/mlkem768_encap_tests.txt",
                "Vendors/BoringSSL/crypto/mlkem/mlkem768_keygen_tests.txt",
                "Vendors/BoringSSL/crypto/mlkem/mlkem768_nist_decap_tests.txt",
                "Vendors/BoringSSL/crypto/mlkem/mlkem768_nist_keygen_tests.txt",
                "Vendors/BoringSSL/crypto/mlkem/mlkem_test.cc",
                "Vendors/BoringSSL/crypto/obj/README",
                "Vendors/BoringSSL/crypto/obj/obj_mac.num",
                "Vendors/BoringSSL/crypto/obj/obj_test.cc",
                "Vendors/BoringSSL/crypto/obj/objects.go",
                "Vendors/BoringSSL/crypto/obj/objects.txt",
                "Vendors/BoringSSL/crypto/pem/pem_test.cc",
                "Vendors/BoringSSL/crypto/perlasm",
                "Vendors/BoringSSL/crypto/pkcs7/pkcs7_test.cc",
                "Vendors/BoringSSL/crypto/pkcs8/pkcs12_test.cc",
                "Vendors/BoringSSL/crypto/pkcs8/pkcs8_test.cc",
                "Vendors/BoringSSL/crypto/pkcs8/test",
                "Vendors/BoringSSL/crypto/poly1305/poly1305_test.cc",
                "Vendors/BoringSSL/crypto/poly1305/poly1305_tests.txt",
                "Vendors/BoringSSL/crypto/pool/pool_test.cc",
                "Vendors/BoringSSL/crypto/rand_extra/fork_detect_test.cc",
                "Vendors/BoringSSL/crypto/rand_extra/getentropy_test.cc",
                "Vendors/BoringSSL/crypto/rand_extra/rand_test.cc",
                "Vendors/BoringSSL/crypto/rand_extra/urandom_test.cc",
                "Vendors/BoringSSL/crypto/refcount_test.cc",
                "Vendors/BoringSSL/crypto/rsa_extra/rsa_test.cc",
                "Vendors/BoringSSL/crypto/self_test.cc",
                "Vendors/BoringSSL/crypto/siphash/siphash_test.cc",
                "Vendors/BoringSSL/crypto/siphash/siphash_tests.txt",
                "Vendors/BoringSSL/crypto/spx/spx_test.cc",
                "Vendors/BoringSSL/crypto/spx/spx_tests.txt",
                "Vendors/BoringSSL/crypto/spx/spx_tests_deterministic.txt",
                "Vendors/BoringSSL/crypto/stack/stack_test.cc",
                "Vendors/BoringSSL/crypto/test",
                "Vendors/BoringSSL/crypto/thread_test.cc",
                "Vendors/BoringSSL/crypto/trust_token/trust_token_test.cc",
                "Vendors/BoringSSL/crypto/x509/tab_test.cc",
                "Vendors/BoringSSL/crypto/x509/test",
                "Vendors/BoringSSL/crypto/x509/x509_test.cc",
                "Vendors/BoringSSL/crypto/x509/x509_time_test.cc",
                "Vendors/BoringSSL/gen/bcm/aesni-gcm-x86_64-win.asm",
                "Vendors/BoringSSL/gen/bcm/aesni-x86-win.asm",
                "Vendors/BoringSSL/gen/bcm/aesni-x86_64-win.asm",
                "Vendors/BoringSSL/gen/bcm/bn-586-win.asm",
                "Vendors/BoringSSL/gen/bcm/co-586-win.asm",
                "Vendors/BoringSSL/gen/bcm/ghash-ssse3-x86-win.asm",
                "Vendors/BoringSSL/gen/bcm/ghash-ssse3-x86_64-win.asm",
                "Vendors/BoringSSL/gen/bcm/ghash-x86-win.asm",
                "Vendors/BoringSSL/gen/bcm/ghash-x86_64-win.asm",
                "Vendors/BoringSSL/gen/bcm/p256-x86_64-asm-win.asm",
                "Vendors/BoringSSL/gen/bcm/p256_beeu-x86_64-asm-win.asm",
                "Vendors/BoringSSL/gen/bcm/rdrand-x86_64-win.asm",
                "Vendors/BoringSSL/gen/bcm/rsaz-avx2-win.asm",
                "Vendors/BoringSSL/gen/bcm/sha1-586-win.asm",
                "Vendors/BoringSSL/gen/bcm/sha1-x86_64-win.asm",
                "Vendors/BoringSSL/gen/bcm/sha256-586-win.asm",
                "Vendors/BoringSSL/gen/bcm/sha256-x86_64-win.asm",
                "Vendors/BoringSSL/gen/bcm/sha512-586-win.asm",
                "Vendors/BoringSSL/gen/bcm/sha512-x86_64-win.asm",
                "Vendors/BoringSSL/gen/bcm/vpaes-x86-win.asm",
                "Vendors/BoringSSL/gen/bcm/vpaes-x86_64-win.asm",
                "Vendors/BoringSSL/gen/bcm/x86-mont-win.asm",
                "Vendors/BoringSSL/gen/bcm/x86_64-mont-win.asm",
                "Vendors/BoringSSL/gen/bcm/x86_64-mont5-win.asm",
                "Vendors/BoringSSL/gen/crypto/aes128gcmsiv-x86_64-win.asm",
                "Vendors/BoringSSL/gen/crypto/chacha-x86-win.asm",
                "Vendors/BoringSSL/gen/crypto/chacha-x86_64-win.asm",
                "Vendors/BoringSSL/gen/crypto/chacha20_poly1305_x86_64-win.asm",
                "Vendors/BoringSSL/gen/crypto/md5-586-win.asm",
                "Vendors/BoringSSL/gen/crypto/md5-x86_64-win.asm",
            ],
            sources: [
                "Vendors/BoringSSL/crypto",
                "Vendors/BoringSSL/gen/bcm",
                "Vendors/BoringSSL/gen/crypto",
                "Vendors/BoringSSL/include",
                "Vendors/BoringSSL/third_party/fiat/asm",
            ],
            resources: [
                .copy("Sources/CBoringSSL/PrivacyInfo.xcprivacy"),
            ],
            publicHeadersPath: "Sources/CBoringSSL/include",
            cSettings: [
                .headerSearchPath("Vendors/BoringSSL/include"),
                // These defines come from BoringSSL's build system
                .define("_HAS_EXCEPTIONS", to: "0", .when(platforms: [.windows])),
                .define("WIN32_LEAN_AND_MEAN", .when(platforms: [.windows])),
                .define("NOMINMAX", .when(platforms: [.windows])),
                .define("_CRT_SECURE_NO_WARNINGS", .when(platforms: [.windows])),
                .define("_XOPEN_SOURCE", to: "700", .when(platforms: [.linux])),
                .define("BORINGSSL_IMPLEMENTATION"),
                // These defines are required on Wasm/WASI, to disable use of pthread.
                .define("OPENSSL_NO_THREADS_CORRUPT_MEMORY_AND_LEAK_SECRETS_IF_THREADED", .when(platforms: [Platform.wasi])),
                .define("OPENSSL_NO_ASM", .when(platforms: [Platform.wasi])),
            ],
            cxxSettings: [
                .headerSearchPath("Vendors/BoringSSL/include"),
                // These defines come from BoringSSL's build system
                .define("_HAS_EXCEPTIONS", to: "0", .when(platforms: [.windows])),
                .define("WIN32_LEAN_AND_MEAN", .when(platforms: [.windows])),
                .define("NOMINMAX", .when(platforms: [.windows])),
                .define("_CRT_SECURE_NO_WARNINGS", .when(platforms: [.windows])),
                .define("_XOPEN_SOURCE", to: "700", .when(platforms: [.linux])),
                .define("BORINGSSL_IMPLEMENTATION"),
                // These defines are required on Wasm/WASI, to disable use of pthread.
                .define("OPENSSL_NO_THREADS_CORRUPT_MEMORY_AND_LEAK_SECRETS_IF_THREADED", .when(platforms: [Platform.wasi])),
                .define("OPENSSL_NO_ASM", .when(platforms: [Platform.wasi])),
            ]
        ),
        .target(
            name: "CCryptoBoringSSLShims",
            dependencies: ["CBoringSSL"],
            exclude: [
                "CMakeLists.txt"
            ],
            resources: [
                .copy("PrivacyInfo.xcprivacy"),
            ],
            swiftSettings: [
                .interoperabilityMode(.Cxx),
            ]
        ),
        .target(
            name: "Crypto",
            dependencies: dependencies,
            exclude: [
                "CMakeLists.txt",
                "AEADs/Nonces.swift.gyb",
                "Digests/Digests.swift.gyb",
                "Key Agreement/ECDH.swift.gyb",
                "Signatures/ECDSA.swift.gyb",
            ],
            resources: [
                .copy("PrivacyInfo.xcprivacy"),
            ],
            swiftSettings: swiftSettings + [.define("MODULE_IS_CRYPTO")]
        ),
        .target(
            name: "_CryptoExtras",
            dependencies: [
                "CBoringSSL",
                "CCryptoBoringSSLShims",
                "CryptoBoringWrapper",
                "Crypto"
            ],
            exclude: [
                "CMakeLists.txt",
            ],
            resources: [
                .copy("PrivacyInfo.xcprivacy"),
            ],
            swiftSettings: swiftSettings + [.interoperabilityMode(.Cxx)]
        ),
        .target(
            name: "CryptoBoringWrapper",
            dependencies: [
                "CBoringSSL",
                "CCryptoBoringSSLShims"
            ],
            exclude: [
                "CMakeLists.txt",
            ],
            resources: [
                .copy("PrivacyInfo.xcprivacy"),
            ],
            swiftSettings: [
                .interoperabilityMode(.Cxx),
            ]
        ),
        .executableTarget(name: "crypto-shasum", dependencies: ["Crypto"]),
        .testTarget(
            name: "CryptoTests",
            dependencies: ["Crypto"],
            resources: [
                .copy("HPKE/hpke-test-vectors.json"),
            ],
            swiftSettings: swiftSettings
        ),
        .testTarget(name: "_CryptoExtrasTests", dependencies: ["_CryptoExtras"]),
    ],
    cLanguageStandard: .gnu11,
    cxxLanguageStandard: .gnucxx14
)
